name: Close Stale Issues
on:
  schedule:
    - cron: '30 8 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale due to inactivity and will be closed in 7 days if no further activity occurs.'
          close-issue-message: 'This issue was closed due to inactivity. Please reopen if you still encounter this problem or have more information to add.'
          stale-pr-message: "This PR hasn't received any updates in a year and will be automatically closed in 30 days. Feel free to re-open if you plan to continue working on this pull request"
          days-before-stale: -1
          days-before-close: -1
          days-before-issue-stale: 14
          days-before-issue-close: 7
          stale-issue-label: 'stale'
          close-issue-label: 'closed-due-to-inactivity'
          exempt-issue-labels: 'do not stale, needs response'
          days-before-pr-stale: 365
          days-before-pr-close: 30
          exempt-pr-labels: 'do not stale'
          only-pr-labels: awaiting-changes,blocked,work-in-progress,awaiting-upstream
          remove-pr-stale-when-updated: true